name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if ! pip show pytest; then pip install pytest; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github --target-version=py310 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest -v -s
